### PR TITLE
added props to team components

### PR DESCRIPTION
**Pull request by codecShivam**
@Mr-Sunglasses sir, I'm happy to report that I have completed this.

### CODE REVIEW

**Comment by Mr-Sunglasses** [comment]
@codecShivam the images are not working in the team's section refer to this website https://deploy-preview-152--fossc.netlify.app/

**Comment by codecShivam** [comment]
> @codecShivam the images are not working in the team's section refer to this website https://deploy-preview-152--fossc.netlify.app/

@Mr-Sunglasses sir, I apologize for any inconvenience my changes may have caused. I am currently working on resolving the problem, and I will submit a revised pull request as soon as possible.

**Comment by codecShivam** [comment]
> @codecShivam the images are not working in the team's section refer to this website https://deploy-preview-152--fossc.netlify.app/

@Mr-Sunglasses Sir, I have fixed the issue and the images are working properly....

**Comment by Mr-Sunglasses** [comment]
Thx @codecShivam

**Pull request merged**
