### PR TITLE
Created a button for doubt schedule in the navbar

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Screenshot from 2023-04-28 15-50-28

### CODE REVIEW

**Comment by akshatcoder-hash** [comment]
Hey @Bharadwajshivam28!
It would be great if the button is like the 'Join Us' one.

image

**Comment by Bharadwajshivam28** [comment]
> Hey @Bharadwajshivam28!
> It would be great if the button is like the 'Join Us' one.
> 
> image
> 

Sure sir just doing it correct

**Comment by Bharadwajshivam28** [comment]
> Hey @Bharadwajshivam28!
> It would be great if the button is like the 'Join Us' one.
> 
> image
> 

It should be in the navbar ?

**Review by akshatcoder-hash — CHANGES_REQUESTED** [review]
Add a button like 'Join Us'
image

**Comment by Bharadwajshivam28** [comment]
> > > Hey @Bharadwajshivam28!
> > > It would be great if the button is like the 'Join Us' one.
> > > image
> > 
> > It should be in the navbar ?
> 
> It should be below the 'Join Us' button with the same style

Sure it will be don in few minutes

**Pull request closed without merging**
