### PR TITLE
Added Privacy Policy page

### PR DESCRIPTION
**Pull request by hiCXK**
# Description

Privacy Policy page has been made and added. @Mr-Sunglasses @akshatcoder-hash Please suggest any changes if required. Also, the issue #122 assigned to @tanishkkkaa can now be completed by linking the 'privacy policy' text on the homepage to the required site. 

Fixes # (issue)

## Added Privacy Policy page (https://fosscu.org/privacypolicy)

- [:heavy_check_mark:] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [:heavy_check_mark:] yarn start

# Checklist:

- [:heavy_check_mark:] My code follows the style guidelines of this project
- [:heavy_check_mark:] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [:heavy_check_mark:] My changes generate no new warnings

### CODE REVIEW

**Comment by hiCXK** [comment]
The preview can be seen on https://deploy-preview-190--fossc.netlify.app/privacypolicy.

**Comment by Mr-Sunglasses** [comment]
Please add the route to the privacy policy page.image

**Comment by hiCXK** [comment]
done :+1: ! @Mr-Sunglasses please review it!

**Review by Mr-Sunglasses — APPROVED** [review]
LGTM 👍🏻

**Comment by Mr-Sunglasses** [comment]
Thanks 🙏 @hiCXK

**Comment by hiCXK** [comment]
Thank you very much!😁❤️

**Pull request merged**
